name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: __jdu=1607244784699714323940; shshshfpa=4806c025-2b17-fe38-086b-a4488b2f1b83-1607244785; shshshfpb=eJjUUU8GTQYDI9W0rIfjdDA%3D%3D; __jdv=122270672|jx3.xoyo.com|-|referral|-|1610116838093; shshshfp=127d78b4c0eccddb83805a039576b50a; mba_muid=1607244784699714323940; __jda=122270672.1607244784699714323940.1607244785.1610116838.1611406440.3; __jdc=122270672; shshshsID=d0cd62b9b29a881462b7f200dd442664_1_1611406443729; 3AB9D23F7A4B3C9B=EC2LDVUGUZCOC76KGR64HJHGHLZJFTD5J7H5WARJQWH5VPSKIV6UTKVOCNM2RQ266PZTG6K2A2CQAZVKPVICEECBXA; jcap_dvzw_fp=MpxI2Ec8ai0fylb62lCwh_3niHNjGexsIzdEJUSXJ7uMjootphsXgmiMnEuRNTghfceZWg==; TrackerID=l2ToRHwvPrf5HEEPWzM7h3Vn48mIMEvHYDEtj-ogH3vM8xBAXjnkFB3krBpNesSnGMzXe_4UJEV756QdTSMbXgBTEqZf7QSYyYIAktHaAls; pt_key=AAJgDByIADBGP4LJvawrwFfvYEsghcrRCHviC_NZV_rniw-6jAWrrz_cRKMR-Vmh_cqhugfepF0; pt_pin=jd_5a140fcd46fb0; pt_token=67sh5cd9; pwdt_id=jd_5a140fcd46fb0; sfstoken=tk01ma5761b97a8sMSsxTWM2dFhPW1Oz2An8D6m4VRUwPESOsbkPNwMhnt+cND/eTsFUQpCxN6lzLPc+RrC7/SWIvE81; mobilev=html5; wxa_level=1; __jdb=122270672.10.1607244784699714323940|3.1611406440; mba_sid=16114064402104838955990008298.10; __jd_ref_cls=Mnpm_ComponentApplied; 
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: SCU16932Tf2ad0aec139bd1301b94c443fbe517fe5a1f8a67646e9
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


